[project]
name = "prisonersdilemma"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.3.4",
    "pettingzoo>=1.25.0",
    "pygame>=2.6.1",
    "torch>=2.9.0",
]
